all:
	# make -f Makefile-asteroids.raspbian
	make -f Makefile-battlezone.raspbian
	make -f Makefile-blackwidow.raspbian
	make -f Makefile-deluxe.raspbian
	make -f Makefile-gravitar.raspbian
	make -f Makefile-lunar.raspbian
	make -f Makefile-redbaron.raspbian
	make -f Makefile-spaceduel.raspbian
	make -f Makefile-tempest.raspbian

clean:
	# make -f Makefile-asteroids.raspbian clean
	make -f Makefile-battlezone.raspbian clean
	make -f Makefile-blackwidow.raspbian clean
	make -f Makefile-deluxe.raspbian clean
	make -f Makefile-gravitar.raspbian clean
	make -f Makefile-lunar.raspbian clean
	make -f Makefile-redbaron.raspbian clean
	make -f Makefile-spaceduel.raspbian clean
	make -f Makefile-tempest.raspbian clean

install:
	sudo make -f Makefile-battlezone.raspbian install
	sudo make -f Makefile-blackwidow.raspbian install
	sudo make -f Makefile-deluxe.raspbian install
	sudo make -f Makefile-gravitar.raspbian install
	sudo make -f Makefile-lunar.raspbian install
	sudo make -f Makefile-redbaron.raspbian install
	sudo make -f Makefile-spaceduel.raspbian install
	sudo make -f Makefile-tempest.raspbian install
